source "https://rubygems.org"

ruby "3.3.4"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "rack-cors"

gem "pg", "~> 1.1"

gem "graphql", "~> 2.2"
gem "bcrypt", "~> 3.1.20"
gem "jwt", "~> 2.8"
gem "csv"

gem "puma", ">= 5.0"





gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false



group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "minitest", "~> 5.22"
end

group :development do
end
